# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Eagle Eyes Search
email: info@eagleeyessearch.com
description: >- # this means to ignore newlines until "baseurl:"
  Eagle Eyes is a computer vision system that helps Search and Rescue teams locate missing persons by drone and in real-time.
baseurl: "/eagle_eyes_website_staging" # the subpath of your site, e.g. /blog
# To deploy to a different environment, override the baseurl when building:
# - For local development: --baseurl=""
# - For staging on GitHub Pages: (set as "/eagle_eyes_website_staging" by default)
# - For production: --baseurl=""
url: "https://eagle-eyes-search.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
future: true 
trailing_slash: true

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
include:
  - ".well-known"  # Used for deep linking to Vocal Coords app

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

google_maps_api_key: AIzaSyA0I_5CibNzcmXlANE1dxLZxJyb4EkFJgk
