name: Deploy Staging Site to eagleeyesears.com

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    name: Deploy to eagleeyesears.com
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Push contents to eagleeyesears.com repo
        run: |
          git remote add staging https://$STAGING_DEPLOY_TOKEN@github.com/Eagle-Eyes-Search/website_staging.git
          git push staging HEAD:main --force
        env:
          STAGING_DEPLOY_TOKEN: ${{ secrets.STAGING_DEPLOY_TOKEN }}
